theme:
  password: shptka_93a7c10fa20e703af4ad52bcb26ec965
  theme_id: 129333330106
  store: vpv-code-challenge.myshopify.com
  ignore_files:
    - settings_data.json
    - src
    - node_modules
    - package.json
    - package-lock.json
